/* 
Print the number of odd and even number from 10 random numbers generated by computer. 
The random number must be from 10 – 100.
*/
package scanner;

import java.util.Random;


public class OddEven {

    public static void main(String[] args) {
       int i,a=1;
       
 
  { 
    Random ran=new Random();
    for(i=1;i<11;i++)//enter the range here by using for loop
    {

    a=ran.nextInt(100) + 10;//gives you any number from 0-10
    System.out.println("The random  number "+i + " is " + a);

   if(a % 2 == 0)
            System.out.println(a + " is even");
        else
            System.out.println(a + " is odd");
    }
  }}}
